name: Add Label 1

on: pull_request

jobs:
  add-label:
    name: Add Label 1

    runs-on: ubuntu-latest

    steps:
    - name: Add Label
      uses: actions/github-script@v7
      with:
        script: |
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['label1']
          });
