name: Add Label 1

on: pull_request

jobs:
  add-label-1:
    name: Add Label 1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: .github

    - name: Add Label
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('./.github/workflows/scripts/add-label-1.js')
          await script({github, context});
