name: ARMAutoSignoff

on:
  # pull_request:
  #   types: [opened, synchronize, reopened, labeled, unlabeled]
  issues:
    types: [labeled, unlabeled]


jobs:
  add-arm-auto-signoff:
    name: ARMAutoSignoff

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        sparse-checkout: |
          .github
          eng

    - name: Add or Remove Label
      uses: actions/github-script@v7
      with:
        script: |
          const armAutoSignoff = require('./.github/workflows/scripts/arm-auto-signoff.js')
          await armAutoSignoff({ github, context, core });
