name: Add ARMAutoSignoff

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]


jobs:
  add-arm-auto-signoff:
    name: Add Label ARMAutoSignoff

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: .github

    - name: Add Label
      uses: actions/github-script@v7
      with:
        script: |
          const addLabel = require('./.github/workflows/scripts/add-label.js')
          await addLabel({ github, context }, "ARMAutoSignoff");
