name: Fail if New Spec

on: pull_request

jobs:
  fail-new-spec:
    name: Fail if New Spec

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - run: |
        CHANGED_SPECS=$(git diff --name-only HEAD^ HEAD | grep ".json$")
        for SPEC in $CHANGED_SPECS; do
          echo $SPEC
          SPEC_DIR=$(dirname $(dirname $(dirname $SPEC)))
          echo $SPEC_DIR
        done
