name: Fail if New Spec

on: pull_request

jobs:
  fail-new-spec:
    name: Fail if New Spec

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        for FILE in $CHANGED_FILES; do
          echo $FILE
        done
