name: Fail Until Label 2

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  fail-until-label-2:
    name: Fail Until Label 2

    runs-on: ubuntu-latest

    steps:
    - name: Fail Until Label 2
      uses: actions/github-script@v7
      with:
        script: |
          const { data: labels } = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
          });

          const labelNames = labels.map(label => label.name);

          if (!labelNames.includes('label2')) {
            core.setFailed('The "label2" label is required on this pull request.');
          }
          else {
            core.info('The "label2" label is present on this pull request.');
          }
